src/Entity/Produit.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * @ORM\Entity(repositoryClass="App\Repository\ProduitRepository")
 * @UniqueEntity("nom")
 */
class Produit
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     * min = 1,
     * max = 255
     * )
     * @Assert\NotNull
     */
    private $nom;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Assert\Length(
     * min = 1,
     * max = 255
     * )
     * @Assert\NotNull
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\GreaterThan(value = 0)
     * @Assert\NotNull
     */
    private $stock;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo;

    /**
     * @ORM\Column(type="integer", nullable=false)
     * @Assert\GreaterThanOrEqual(value = 0)
     */
    private $Prix;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Contenupanier", inversedBy="Produit")
     */
    private $contenupanier;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): self
    {
        $this->stock = $stock;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->Prix;
    }

    public function setPrix(int $Prix): self
    {
        $this->Prix = $Prix;

        return $this;
    }

    public function getContenupanier(): ?Contenupanier
    {
        return $this->contenupanier;
    }

    public function setContenupanier(?Contenupanier $contenupanier): self
    {
        $this->contenupanier = $contenupanier;

        return $this;
    }
}

src/Form/ProduitType.php
<?php

namespace App\Form;

use App\Entity\Produit;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Contracts\Translation\TranslatorInterface;



class ProduitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('description')
            ->add('stock')
            ->add('photoUpload', FileType::class, [
                'label' => 'Photo',
                'translation_domain' => 'messages',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'image/jpg',
                            'image/jpeg',
                            'image/png',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid image',
                    ])
                ],
            ])
            ->add('Prix')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Produit::class,
        ]);
    }
}

src/Controller/ProduitController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Form\ProduitType;
use App\Repository\ProduitRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;
use Symfony\Component\HttpFoundation\File\Exception\FileException;

/**
 * @Route("/{_locale}")
 */
class ProduitController extends AbstractController
{
    /**
     * @Route("/", name="produit_index", methods={"GET","POST"})
     * Page d'accueil
     */
    public function index(ProduitRepository $produitRepository, Request $request, TranslatorInterface $translator): Response
    {
        $produit = new Produit();
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $fichier = $form->get('photoUpload')->getData();
            if ($fichier) {//Creation de l'extension et envoi de la photo
                $nomFichier = uniqid() . '.' . $fichier->guessExtension();

                try {
                    $fichier->move(
                        $this->getParameter('upload_dir'),
                        $nomFichier
                    );
                } catch (FileException $e) {
                    $this->addFlash("danger", $translator->trans('fichier.erreur'));
                    return $this->redirectToRoute('home');
                }
                $produit->setPhoto($nomFichier);
                $this->addFlash("success", $translator->trans('flash.produit.cree'));
            }
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($produit);
            $entityManager->flush();

            return $this->redirectToRoute('produit_index');
        }
        return $this->render('produit/index.html.twig', [// Ce qu'on va afficher dans l'accueil
            'produits' => $produitRepository->findAll(),
            'produit' => $produit,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/produit/{id}", name="produit_show", methods={"GET"})
     * Page d'un produit
     */
    public function show(Produit $produit): Response
    {
        return $this->render('produit/produit.html.twig', [
            'produit' => $produit,
        ]);
    }

    /**
     * @Route("/produit/{id}/edit", name="produit_edit", methods={"GET","POST"})
     * Page de modification d'un produit
     */
    public function edit(Request $request, Produit $produit, TranslatorInterface $translator): Response
    {
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('produit_index');
        }

        return $this->render('produit/edit.html.twig', [
            'produit' => $produit,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="produit_delete", methods={"DELETE"})
     * Page de suppression d'un produit
     */
    public function delete(Request $request, Produit $produit, TranslatorInterface $translator): Response
    {
        if ($this->isCsrfTokenValid('delete'.$produit->getId(), $request->request->get('_token'))) {
            if ($produit->getPhoto() != null) {// On delink et supprime l'image si elle est en local.
                unlink($this->getParameter('upload_dir') . $produit->getPhoto());
            }
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($produit);
            $entityManager->flush();
            $this->addFlash('success', $translator->trans('flash.produit.supprimer'));
        }

        return $this->redirectToRoute('produit_index');
    }
}

templates/produit/_delete_form.html.twig
<form method="post" action="{{ path('produit_delete', {'id': produit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit.id) }}">
    <button class="btn">{{'produit.supprimer'|trans}}</button>
</form>

templates/produit/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn  btn-info">{{ button_label|default('Ajouter') }}</button>
{{ form_end(form) }}

templates/produit/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{'produit.modifiertitre'|trans}}{% endblock %}

{% block body %}
    <h1>{{'produit.modifiertitre'|trans}}</h1>

    {{ include('produit/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('produit_index') }}">{{'produit.retour'|trans}}</a>

    {{ include('produit/_delete_form.html.twig') }}
{% endblock %}

templates/produit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{'produit.titre'|trans}}{% endblock %}

{% block body %}
    <h1>{{'produit.titre'|trans}}</h1>

    <table class="table">
        <thead>
            <tr>
                <th>{{'produit.nom'|trans}}</th>
                <th>{{'produit.description'|trans}}</th>
                <th>{{'produit.stock'|trans}}</th>
                <th>{{'produit.photo'|trans}}</th>
                <th>{{'produit.prix'|trans}}</th>
            </tr>
        </thead>
        <tbody>
        {% for produit in produits %}
            <tr>
                <td>{{ produit.nom }}</td>
                <td>{{ produit.description }}</td>
                <td>{{ produit.stock }}</td>
                <td><img src="{{ asset('uploads/' ~ produit.photo) }}"></td>
                <td>{{ produit.Prix }}€</td>
                <td>
                    <a href="{{ path('produit_show', {'id': produit.id}) }}">Voir</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">{{'produit.noproduit'|trans}}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {# Si on est admin on pourra créer un produit #}

    {% if is_granted('ROLE_ADMIN')%}

    <h2>{{'produit.ajouter'|trans}}</h2>

    {{ include('produit/_form.html.twig') }}

    {% endif %}

{% endblock %}

templates/produit/produit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit{% endblock %}

{% block body %}
    <h1>Produit</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ produit.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ produit.nom }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ produit.description }}</td>
            </tr>
            <tr>
                <th>Stock</th>
                <td>{{ produit.stock }}</td>
            </tr>
            <tr>
                <th>Photo</th>
                <td><img src="{{ asset('uploads/' ~ produit.photo) }}"></td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ produit.Prix }}</td>
            </tr>
        </tbody>
    </table>
    {# Si on est admin on pourra modifier ou supprimer le produit #}
    {% if is_granted('ROLE_ADMIN')%} 
    <a href="{{ path('produit_edit', {'id': produit.id}) }}">{{'produit.modifier'|trans}}</a>
    {{ include('produit/_delete_form.html.twig') }}

    {% endif %}
{% endblock %}

templates/produit/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit{% endblock %}

{% block body %}
    <h1>Produit</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ produit.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ produit.nom }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ produit.description }}</td>
            </tr>
            <tr>
                <th>Stock</th>
                <td>{{ produit.stock }}</td>
            </tr>
            <tr>
                <th>Photo</th>
                <td>{{ produit.photo }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ produit.Prix }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('produit_index') }}">back to list</a>

    <a href="{{ path('produit_edit', {'id': produit.id}) }}">edit</a>

    {{ include('produit/_delete_form.html.twig') }}
{% endblock %}